version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: max_inventory_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: max_inventory
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
